name: Docker debian
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  debian_build_job:
    runs-on: ubuntu-latest
    name: Debian build
    steps:
    - uses: actions/checkout@v3
    - name: Debian docker action
      uses: ./
      id: build
